### ISSUE TITLE
checkpoint problems

### ISSUE THREAD

**Issue by hosseinab** [muthu-kc/php-instagram-private-api-with-checkpoint-feature#2]
hi
i want login to my instagram page . when call login function and checkpoint returns this array to output : 
{"loggedInUser":[],"cookies":{"rur":"FTW","csrftoken":"Rp8Zdp********64RA","mid":"WxbPwAAB*********BEuyTmA","urlgen":"\"{\\\"time\\\": 1528221630}:1fQGFz:ZWzgsJQQyWANLsmzxaGFsQUCsn8\"","mcd":"3","ds_user_id":"5775151683","sessionid":"IGSC260f721945f******************************************7XLh5cbQ3FA19JirmfISb3O87fzy3IA0%3A%7B%22_auth_user_id%22%3A5775151683%2C%22_auth_user_backend%22%3A%22accounts.backends.CaseInsensitiveModelBackend%22%2C%22_auth_user_hash%22%3A%22%22%2C%22_platform%22%3A4%2C%22_token_ver%22%3A2%2C%22_token%22%3A%225775151683%3A1aeGFJvqaQzkFY6YgGYffbjrIdVnVzmu%3A0e78408a85901dd7bbc532a6bbf008a539c561c69360a50ca0b3c2563b1ba2df%22%2C%22last_refreshed%22%3A1528221762.3165283203%7D"},"csrfToken":"Rp8ZdpkR************Oc64RA","rankToken":"7c59ddac-b81d-4d54-8f51-42b438578650","phoneId":"be9661d9-1339-45e8-b85e-8cbb55a6c627","deviceId":"android-1e074b6e12573dc6","guid":"98c202d7-2c81-41cc-a841-4b57f39f5271","uuid":"98c202d7-2c81-41cc-a841-4b57f39f5271","googleAdId":"70ebb707-e368-44c0-aeec-19ecdfd53f2e"}
 
when call follow request my output is : 
Failed to followUser: [fail] login_required

sorry for my bad endglish
best regards

**Comment by adiv-phpian** [comment]
@hosseinab please follow same flow present in the example code. I think you are missed to set logged in user id before saving the session.

**Comment by hosseinab** [comment]
thanks a lot my friend . this works.
