### ISSUE TITLE
Not getting verification code

### ISSUE THREAD

**Issue by kamaldeep7** [muthu-kc/php-instagram-private-api-with-checkpoint-feature#6]
I have tested more than 10-15 accounts which are added successfully without verification code. But at the time of challenge, it's not adding any accounts. 

it's throwing error : - ( phone and email both are attached ) and accounts are older too. 

Notice: Undefined offset: 1 in /var/www/html/checkpoint/example/login.php on line 35

Notice: Trying to get property of non-object in /var/www/html/checkpoint/example/login.php on line 35

Notice: Trying to get property of non-object in /var/www/html/checkpoint/example/login.php on line 35

Notice: Trying to get property of non-object in /var/www/html/checkpoint/example/login.php on line 35

Notice: Trying to get property of non-object in /var/www/html/checkpoint/example/login.php on line 35

Notice: Trying to get property of non-object in /var/www/html/checkpoint/example/login.php on line 37
verification code sent to 
Notice: Trying to get property of non-object in /var/www/html/checkpoint/example/verification_form.php on line 20
check and enter the verification code.

**Comment by adiv-phpian** [comment]
Did you get an email verification code?

**Comment by adiv-phpian** [comment]
By default, it will send email to a user who configured the only email.  on the login page line 35, you can select verification method and pass the id of whatever method you want to the verification form.

**Comment by kamaldeep7** [comment]
Thanks alot. 

Issues resolved. do you have a skype?

i may have some work for you.

**Comment by kamaldeep7** [comment]
it will be a paid task. let me know if you are interested.  Please add me skype. my skype username : - lazyweb.in ( kamal deep )
